# Chart Testing Configuration
chart-dirs:
  - charts

# Helm configuration
helm-extra-args: --timeout 600s --debug
debug: true

# Target Kubernetes version for testing
target-branch: main

# Additional validation
validate-maintainers: false
check-version-increment: false

# Change detection
all: false
remote: origin
since: HEAD~1

# Lint configuration
lint-conf: charts/ci/.yamllint