---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - cronschedules.elbazi.co
  resources:
  - cronjobscaledowns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cronschedules.elbazi.co
  resources:
  - cronjobscaledowns/finalizers
  verbs:
  - update
- apiGroups:
  - cronschedules.elbazi.co
  resources:
  - cronjobscaledowns/status
  verbs:
  - get
  - patch
  - update
