apiVersion: cronschedules.elbazi.co/v1
kind: CronJobScaleDown
metadata:
  name: nginx-dev-testing
  namespace: default
spec:
  targetRef:
    name: nginx-test
    namespace: default
    kind: Deployment
    apiVersion: apps/v1
  # Scale down every 30 seconds (for development testing)
  scaleDownSchedule: "*/30 * * * * *"
  # Scale up every 45 seconds (for development testing)
  scaleUpSchedule: "*/45 * * * * *"
  timeZone: "UTC"
