apiVersion: cronschedules.elbazi.co/v1
kind: CronJobScaleDown
metadata:
  name: nginx-quick-test
  namespace: default
spec:
  targetRef:
    name: nginx-test
    namespace: monitoring
    kind: Deployment
    apiVersion: apps/v1
  # Scale down at second 0 of every minute (should trigger immediately if we're past second 0)
  scaleDownSchedule: "0 * * * * *"
  # Scale up at second 30 of every minute
  scaleUpSchedule: "30 * * * * *"
  timeZone: "UTC"
