apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-web-app
  template:
    metadata:
      labels:
        app: sample-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: cronschedules.elbazi.co/v1
kind: CronJobScaleDown
metadata:
  name: sample-web-app-scaler
  namespace: default
spec:
  targetRef:
    name: sample-web-app
    namespace: default
    kind: Deployment
    apiVersion: apps/v1
  # Scale down every day at 10 PM
  scaleDownSchedule: "0 0 22 * * *"
  # Scale up every day at 6 AM
  scaleUpSchedule: "0 0 6 * * *"
  timeZone: "UTC"
